# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 500)
        MainWindow.setMinimumSize(QtCore.QSize(300, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/calculator.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"                color: white;\n"
"                background-color: #121212;\n"
"                font-family: Rubik;\n"
"                font-size: 16pt;\n"
"                font-weight: 600;\n"
"                }\n"
"\n"
"                QPushButton {\n"
"                background-color: transparent;\n"
"                border: none;\n"
"                }\n"
"\n"
"                QPushButton:hover {\n"
"                background-color: #666;\n"
"                }\n"
"\n"
"                QPushButton:pressed {\n"
"                background-color: #888;\n"
"                }\n"
"            ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_methods = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.list_methods.setFont(font)
        self.list_methods.setStyleSheet("font: 25 11pt \"Ubuntu\";")
        self.list_methods.setObjectName("list_methods")
        self.verticalLayout.addWidget(self.list_methods)
        self.list_input = QtWidgets.QListWidget(self.centralwidget)
        self.list_input.setStyleSheet("font: 12pt \"Ubuntu Mono\";")
        self.list_input.setObjectName("list_input")
        self.verticalLayout.addWidget(self.list_input)
        self.layout_output = QtWidgets.QHBoxLayout()
        self.layout_output.setObjectName("layout_output")
        self.le_entry = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_entry.sizePolicy().hasHeightForWidth())
        self.le_entry.setSizePolicy(sizePolicy)
        self.le_entry.setStyleSheet("font-size: 40pt;\n"
"                                border: none;\n"
"                            ")
        self.le_entry.setMaxLength(16)
        self.le_entry.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.le_entry.setReadOnly(True)
        self.le_entry.setObjectName("le_entry")
        self.layout_output.addWidget(self.le_entry)
        self.img_grafic = QtWidgets.QLabel(self.centralwidget)
        self.img_grafic.setObjectName("img_grafic")
        self.layout_output.addWidget(self.img_grafic)
        self.verticalLayout.addLayout(self.layout_output)
        self.lbl_temp = QtWidgets.QLabel(self.centralwidget)
        self.lbl_temp.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_temp.sizePolicy().hasHeightForWidth())
        self.lbl_temp.setSizePolicy(sizePolicy)
        self.lbl_temp.setStyleSheet("color: #888;")
        self.lbl_temp.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lbl_temp.setObjectName("lbl_temp")
        self.verticalLayout.addWidget(self.lbl_temp)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "shtosh calculator"))
        self.le_entry.setText(_translate("MainWindow", "0"))
        self.img_grafic.setText(_translate("MainWindow", "TextLabel"))
